// Design tokens and constants from Figma design

export const COLORS = {
  // Primary colors
  primary: {
    50: '#F5F3FF',
    100: '#EDE9FE',
    200: '#DDD6FE',
    300: '#C4B5FD',
    400: '#A78BFA',
    500: '#8B5CF6',
    600: '#7C3AED',
    700: '#6D28D9',
    800: '#5B21B6',
    900: '#4C1D95',
  },
  // Blue accent color
  accent: '#4A4AEF',
  // Text colors
  text: {
    primary: '#1E1B4B',
    secondary: '#6B7280',
    light: '#9CA3AF',
  },
  // Background colors
  background: {
    white: '#FFFFFF',
    light: '#F9FAFB',
    dark: '#1F2937',
  },
} as const;

export const CATEGORIES = [
  { id: 'design', name: 'Design', icon: 'design', jobs: 235 },
  { id: 'sales', name: 'Sales', icon: 'sales', jobs: 756 },
  { id: 'marketing', name: 'Marketing', icon: 'marketing', jobs: 140 },
  { id: 'finance', name: 'Finance', icon: 'finance', jobs: 325 },
  { id: 'technology', name: 'Technology', icon: 'technology', jobs: 436 },
  { id: 'engineering', name: 'Engineering', icon: 'engineering', jobs: 542 },
  { id: 'business', name: 'Business', icon: 'business', jobs: 211 },
  { id: 'hr', name: 'Human Resource', icon: 'hr', jobs: 346 },
] as const;

export const COMPANIES = [
  { id: 'vodafone', name: 'Vodafone' },
  { id: 'intel', name: 'Intel' },
  { id: 'tesla', name: 'Tesla' },
  { id: 'amd', name: 'AMD' },
  { id: 'talkkit', name: 'Talkkit' },
] as const;

export const FEATURED_JOBS = [
  {
    id: 1,
    title: 'Email Marketing',
    company: 'Revolut',
    location: 'Madrid, Spain',
    description: 'Revolut is looking for Email Marketing to help team manage and optimize email campaigns.',
    type: 'Full Time',
    tags: ['Marketing', 'Design'],
    logo: 'revolut',
  },
  {
    id: 2,
    title: 'Brand Designer',
    company: 'Dropbox',
    location: 'San Francisco, US',
    description: 'Dropbox is looking for Brand Designer to help the team to create visual brand identity.',
    type: 'Full Time',
    tags: ['Design', 'Business'],
    logo: 'dropbox',
  },
  {
    id: 3,
    title: 'Email Marketing',
    company: 'Pitch',
    location: 'Berlin, Germany',
    description: 'Pitch is looking for Customer Manager to join marketing team.',
    type: 'Full Time',
    tags: ['Marketing'],
    logo: 'pitch',
  },
  {
    id: 4,
    title: 'Visual Designer',
    company: 'Blinkist',
    location: 'Granada, Spain',
    description: 'Blinkist is looking for Visual Designer to help team design visual content.',
    type: 'Full Time',
    tags: ['Design'],
    logo: 'blinkist',
  },
  {
    id: 5,
    title: 'Product Designer',
    company: 'ClassPass',
    location: 'Manchester, UK',
    description: 'ClassPass is looking for Product Designer to help us create amazing products.',
    type: 'Full Time',
    tags: ['Marketing', 'Design'],
    logo: 'classpass',
  },
  {
    id: 6,
    title: 'Lead Designer',
    company: 'Canva',
    location: 'Ontario, Canada',
    description: 'Canva is looking for Lead Engineer to develop new features.',
    type: 'Full Time',
    tags: ['Design', 'Business'],
    logo: 'canva',
  },
  {
    id: 7,
    title: 'Brand Strategist',
    company: 'GoDaddy',
    location: 'Marseille, France',
    description: 'GoDaddy is looking for Brand Strategist to join the team.',
    type: 'Full Time',
    tags: ['Marketing'],
    logo: 'godaddy',
  },
  {
    id: 8,
    title: 'Data Analyst',
    company: 'Twitter',
    location: 'San Diego, US',
    description: 'Twitter is looking for Data Analyst to help team design data solutions.',
    type: 'Full Time',
    tags: ['Technology'],
    logo: 'twitter',
  },
] as const;

export const LATEST_JOBS = [
  {
    id: 1,
    title: 'Social Media Assistant',
    company: 'Nomad',
    location: 'Paris, France',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'nomad',
  },
  {
    id: 2,
    title: 'Brand Designer',
    company: 'Dropbox',
    location: 'San Francisco, USA',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'dropbox',
  },
  {
    id: 3,
    title: 'Interactive Developer',
    company: 'Terraform',
    location: 'Hamburg, Germany',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'terraform',
  },
  {
    id: 4,
    title: 'HR Manager',
    company: 'Packer',
    location: 'Lucern, Switzerland',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'packer',
  },
  {
    id: 5,
    title: 'Social Media Assistant',
    company: 'Netlify',
    location: 'Paris, France',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'netlify',
  },
  {
    id: 6,
    title: 'Brand Designer',
    company: 'Maze',
    location: 'San Francisco, USA',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'maze',
  },
  {
    id: 7,
    title: 'Interactive Developer',
    company: 'Udacity',
    location: 'Hamburg, Germany',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'udacity',
  },
  {
    id: 8,
    title: 'HR Manager',
    company: 'Webflow',
    location: 'Lucern, Switzerland',
    type: 'Full-Time',
    tags: ['Marketing', 'Design'],
    logo: 'webflow',
  },
] as const;
